config/routes.rb
TechLendingApp::Application.routes.draw do
  resources :checkouts

  resources :items

end

app/models/checkout.rb
class Checkout < ActiveRecord::Base
  attr_accessible :date, :duration, :end_time, :id, :item_id, :patron_college, :patron_status, :renewals, :start_time, :transaction_id, :call_number, :created_at, :updated_at
  
  def self.total_on(date)
      where("date(date) = ?",date).count
    end 
    
    def self.status_total(status)
      where("patron_status = ?", status).count
    end  
    
    def self.college_total(college)
      where("patron_college = ?", college).count
    end
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :call_number, :id, :location, :name, :created_at, :updated_at
  has_many :checkouts
  
  def self.get_item_call_number
      @cns = []
      Item.all.each do |item|
        @cns << item.call_number 
      end
      @cns.uniq.sort
   end
  
   def self.get_patron_status
      @statuses = []
        Item.all.each do |item|
            if !item.checkouts.empty?
            item.checkouts.each do |co|
              @statuses << co.patron_status
            end
          end  
        end
        @statuses.uniq.sort
    end
    
    def self.get_patron_college
       @colleges = []
        Item.all.each do |item|
          if !item.checkouts.empty?
          item.checkouts.each do |co|
            @colleges << co.patron_college
            end
          end  
        end
        @colleges.uniq.sort
     end
     
     def self.get_co_date
        @dates = []
        Item.all.each do |item|
          item.checkouts do |co|
            @dates << co.date
          end  
        end
        @cos.uniq
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  # GET /checkouts
  # GET /checkouts.json
  def index  
    require 'csv'
    @q = Checkout.search(params[:q])
    @checkouts = @q.result(:distinct => true).paginate(:page =>params[:page], :per_page => 50)
    respond_to do |format|
      format.html # index.html.erb  
      format.json { render :json => @checkouts }
      format.csv do
	      @checkouts = @q.result(:distinct => true)
       	csv_string = CSV.generate do |csv|
      	   #header
      	   csv << ["call number", "checkout date", "start time", "end time", "patron status", "patron college", "renewals"]
      	   @checkouts.each do |co|
            #data rows
        		 csv << [co.call_number, co.date, co.start_time, co.end_time, co.patron_status, co.patron_college, co.renewals]
           end
      	end
          #send to browser
  	        send_data csv_string, :type =>'text/csv; charset=iso-8859-1; header=present', :disposition => "attachment; filename=checkouts.csv"
      end	
    end
  end

  # GET /checkouts/1
  # GET /checkouts/1.json
  def show
    @checkout = Checkout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checkout }
    end
  end

  # GET /checkouts/new
  # GET /checkouts/new.json
  def new
    @checkout = Checkout.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @checkout }
    end
  end

  # GET /checkouts/1/edit
  def edit
    @checkout = Checkout.find(params[:id])
  end

  # POST /checkouts
  # POST /checkouts.json
  def create
    @checkout = Checkout.new(params[:checkout])

    respond_to do |format|
      if @checkout.save
        format.html { redirect_to @checkout, notice: 'Checkout was successfully created.' }
        format.json { render json: @checkout, status: :created, location: @checkout }
      else
        format.html { render action: "new" }
        format.json { render json: @checkout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checkouts/1
  # PUT /checkouts/1.json
  def update
    @checkout = Checkout.find(params[:id])

    respond_to do |format|
      if @checkout.update_attributes(params[:checkout])
        format.html { redirect_to @checkout, notice: 'Checkout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @checkout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkouts/1
  # DELETE /checkouts/1.json
  def destroy
    @checkout = Checkout.find(params[:id])
    @checkout.destroy

    respond_to do |format|
      format.html { redirect_to checkouts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
      require 'csv'
      @q = Item.includes(:checkouts).search(params[:q])
      @items = @q.result(:distinct => true)
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @checkouts }
        format.csv do
  	      @items = @q.result(:distinct => true)
         	csv_string = CSV.generate do |csv|
        	   #header
        	   csv << ["call number", "location", "checkout date", "start time", "end time", "patron status", "patron college", "renewals"]
        	   @items.each do |item|
        	     if !item.checkouts.empty?
        	       item.checkouts.each do |co|
                   #data rows
              		 csv << [item.call_number, item.location, co.date, co.start_time, co.end_time, co.patron_status, co.patron_college, co.renewals]
            	   end 
               end
             end
        	end
            #send to browser
    	      send_data csv_string, :type =>'text/csv; charset=iso-8859-1; header=present', :disposition => "attachment; filename=letters.csv"
        end	
      end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/checkouts/_form.html.erb
<%= form_for(@checkout) do |f| %>
  <% if @checkout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checkout.errors.count, "error") %> prohibited this checkout from being saved:</h2>

      <ul>
      <% @checkout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br />
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :patron_status %><br />
    <%= f.text_field :patron_status %>
  </div>
  <div class="field">
    <%= f.label :patron_college %><br />
    <%= f.text_field :patron_college %>
  </div>
  <div class="field">
    <%= f.label :renewals %><br />
    <%= f.number_field :renewals %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checkouts/edit.html.erb
<h1>Editing checkout</h1>

<%= render 'form' %>

<%= link_to 'Show', @checkout %> |
<%= link_to 'Back', checkouts_path %>

app/views/checkouts/index.html.erb
<%= search_form_for @q do |f| %>
<div id="search">
 <div id="item_info">
 	<h2>Search By Item Info</h2>
 		<p> <%= f.label "Item Name Contains" %>
  		<%= f.text_field :call_number_cont, :size => 20 %></p>
 </div>
 <div id="patron_info">
 	<h2>Search By Patron Info</h2>
 	<p> <%= f.label "Status" %><%= f.select :patron_status_eq, ["FACULTY", "FR", "GRAD", "GRAD-NCSU-DIST", "JR", "NCSU-DIST-FR", "NCSU-DIST-JR", "NCSU-DIST-SO", "NCSU-DIST-SR", "SO", "SR", "STAFF", "TRLN", "UNDERGRAD"], :include_blank => true %></p>
  	<p><%= f.label "College" %><%= f.select :patron_college_eq, ['UNCHASS', 'UNMGMT', 'UNENGR'], :include_blank => true %></p>
 </div>
 <div id="date_received">
 	<h2>Search By Checkout Info</h2>
 	<p> <%= f.label "Date" %><%= f.text_field :date_eq, :size => 10 %></p>
  	<p><%= f.label "Date Range " %><%= f.text_field :date_gteq , :size => 10 %><%= f.text_field :date_lteq, :size => 10 %>
 </div>
</div>
<div id="buttons">
 <div class="example1" id="submit_search"> <%= f.submit %></div> <div class="example1"><span><%= link_to "Clear Search", checkouts_path %></span></div> <div class="example1"><span><%= link_to "Download Results", :action => "index", :q => params[:q], :format => :csv %></span></div>
</div>
<% end %>
<div id="body">
<h2><span style="color:red">Number of Checkouts: <%= @checkouts.count %></span></h2>
<% if @checkouts.empty? %>
  <h2> <span style="font-size:18pt; color:grey">There are no checkouts that match your query</span></h2>
<% else %>
<p>Sort By: <%= sort_link @q, :date, "Date" %></p>

<table id="main">
  <tr>
    <th>Call Number</th>
    <th>Date</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Duration</th>
    <th>Patron status</th>
    <th>Patron college</th>
    <th>Renewals</th>
  </tr>
<p><%= will_paginate @checkouts %></p>
<h2>View Charts</h2>
<%= link_to_function "Checkouts Over Time", "$('#checkouts_chart').toggle()" %> | <%= link_to_function "Checkouts By Patron Status", "$('#status_chart').toggle()" %><br />
<div id='checkouts_chart' style='width: 1750px; height: 700px; display:none'>
	<script type='text/javascript' charset='utf-8'>
	  $(function () {
	    new Highcharts.Chart({
		    chart: { renderTo: 'checkouts_chart' },
		    title: { text: 'Checkouts over Time' },
		    xAxis: { type: 'datetime' },
		    yAxis: {
			  min: 0,
		      title: { text: 'Checkouts'}
		    },
			tooltip: {
			      formatter: function () {
			        return Highcharts.dateFormat('%A, %B %e, %Y', this.x) + ': ' +
			          Highcharts.numberFormat(this.y, 0);
			      }
			    },
		    series: [{
			  name: 'Checkouts',
			  pointInterval: 24 * 3600 * 1000,
			  pointStart: Date.UTC(2010, 07, 10),
		      data: <%= ((Date.new(2012,10,24) - 806).to_date..(Date.today - 5).to_date).map { |date| @checkouts.where(:date => date).count}.inspect %>
		    }]
		  });
		});
	</script>
	</div>
	<br />
	<div id='status_chart' style='width: 1750px; height: 700px; display:none'>
		<script type='text/javascript' charset='utf-8'>
		$(function () {
		    new Highcharts.Chart({
		            chart: {
		                renderTo: 'status_chart',
		                type: 'column',
		                margin: [ 50, 50, 100, 80]
		            },
		            title: {
		                text: 'Checkouts By Status'
		            },
		            xAxis: {
		                categories: ["FACULTY", "FR", "GRAD", "GRAD-NCSU-DIST", "JR", "NCSU-DIST-FR", "NCSU-DIST-JR", "NCSU-DIST-SO", "NCSU-DIST-SR", "SO", "SR", "STAFF", "TRLN", "UNDERGRAD"],
		                labels: {
		                    rotation: -45,
		                    align: 'right',
		                    style: {
		                        fontSize: '13px',
		                        fontFamily: 'Verdana, sans-serif'
		                    }
		                }
		            },
		            yAxis: {
		                min: 0,
		                title: {
		                    text: 'Number of Checkouts'
		                }
		            },
		            legend: {
		                enabled: false
		            },
		            tooltip: {
		                formatter: function() {
		                    return '<b>'+ this.x +'</b><br/>'+
		                        'Checkouts: '+ Highcharts.numberFormat(this.y, 0);
		                }
		            },
		            series: [{
		                name: 'Status',
		                data:  <%= ["FACULTY", "FR", "GRAD", "GRAD-NCSU-DIST", "JR", "NCSU-DIST-FR", "NCSU-DIST-JR", "NCSU-DIST-SO", "NCSU-DIST-SR", "SO", "SR", "STAFF", "TRLN", "UNDERGRAD"].map { |status| @checkouts.where(:patron_status =>status).count}.inspect %>,
		                dataLabels: {
		                    enabled: true,
		                    rotation: -90,
		                    color: '#FFFFFF',
		                    align: 'right',
		                    x: 4,
		                    y: 10,
		                    style: {
		                        fontSize: '13px',
		                        fontFamily: 'Verdana, sans-serif'
		                    }
		                }
		            }]
		        });
		    });
		
		</script>
		</div>
	
<% @checkouts.each do |checkout| %>
  <tr class="<%= cycle("odd", "even") -%>">
    <td><%= checkout.call_number %></td>
    <td><%= checkout.date %></td>
    <td><%= checkout.start_time %></td>
    <td><%= checkout.end_time %></td>
    <td><%= checkout.duration %></td>
    <td><%= checkout.patron_status %></td>
    <td><%= checkout.patron_college %></td>
    <td><%= checkout.renewals %></td>
  </tr>
<% end %>
</table>
<% end %>
<br />

app/views/checkouts/new.html.erb
<h1>New checkout</h1>

<%= render 'form' %>

<%= link_to 'Back', checkouts_path %>

app/views/checkouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @checkout.id %>
</p>

<p>
  <b>Item:</b>
  <%= @checkout.item_id %>
</p>

<p>
  <b>Date:</b>
  <%= @checkout.date %>
</p>

<p>
  <b>Start time:</b>
  <%= @checkout.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @checkout.end_time %>
</p>

<p>
  <b>Duration:</b>
  <%= @checkout.duration %>
</p>

<p>
  <b>Patron status:</b>
  <%= @checkout.patron_status %>
</p>

<p>
  <b>Patron college:</b>
  <%= @checkout.patron_college %>
</p>

<p>
  <b>Renewals:</b>
  <%= @checkout.renewals %>
</p>


<%= link_to 'Edit', edit_checkout_path(@checkout) %> |
<%= link_to 'Back', checkouts_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :call_number %><br />
    <%= f.text_field :call_number %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= search_form_for @q do |f| %>
<div id="search">
 <div id="item_info">
 <h2>Search By Item Info</h2>
 <p> <%= f.label "Call Number" %>
  <%= f.select :call_number_eq, Item.get_item_call_number, :size => 20 %></p>
</div>
<div id="buttons">
 <div class="example1" id="submit_search"> <%= f.submit %></div> <div class="example1"><span><%= link_to "Clear Search", items_path %></span></div> <div class="example1"><span><%= link_to "Download Results", :action => "index", :q => params[:q], :format => :csv %></span></div>
</div>
<% end %>
<div id="body">
<h2><span style="color:red">Number of Items: <%= @items.count %></span></h2>
<% if @items.empty? %>
  <h2> <span style="font-size:18pt; color:grey">There are no letters that match you query</span></h2>
<% else %>
<table id="main">
  <tr>
    <th>Item</th>
	<th>Call Number</th>
    <th>Location</th>
  </tr>
<% @items.each do |item| %>
<br />
<h2>View Charts</h2>
<%= link_to_function "Checkouts Over Time", "$('#item_checkout').toggle()" %> | <%= link_to_function "Checkouts By Patron Status", "$('#status_chart').toggle()" %><br /><br />
<div id="item_checkout" style='width: 1750px; height: 700px; display:none'>
	<script type="text/javascript" charset="utf-8">
	  $(function () {
	    new Highcharts.Chart({
		    chart: { renderTo: 'item_checkout' },
		    title: { text: 'Checkouts over Time' },
		    xAxis: { type: 'datetime' },
		    yAxis: {
			  min: 0,
			  tickInterval: 1,
		      title: { text: 'Checkouts'}
		    },
		    series: [{
			  	name: 'Checkouts',
				pointInterval: 24 * 3600 * 1000,
				pointStart: Date.UTC(<%= item.checkouts.first.date.to_time.to_s.split(' ')[0].gsub('-', ', ' ) %>),
		      	data: <%= (item.checkouts.first.date..item.checkouts.last.date).map { |date| item.checkouts.where(:date => date).count}.inspect %>
		    }]
		  });
		});
	</script>
	
</div>
<div id='status_chart' style='width: 1750px; height: 700px; display:none'>
	<script type='text/javascript' charset='utf-8'>
	$(function () {
	    new Highcharts.Chart({
	            chart: {
	                renderTo: 'status_chart',
	                type: 'column',
	                margin: [ 50, 50, 100, 80]
	            },
	            title: {
	                text: 'Checkouts By Status'
	            },
	            xAxis: {
	                categories: ["FACULTY", "FR", "GRAD", "GRAD-NCSU-DIST", "JR", "NCSU-DIST-FR", "NCSU-DIST-JR", "NCSU-DIST-SO", "NCSU-DIST-SR", "SO", "SR", "STAFF", "TRLN", "UNDERGRAD"],
	                labels: {
	                    rotation: -45,
	                    align: 'right',
	                    style: {
	                        fontSize: '13px',
	                        fontFamily: 'Verdana, sans-serif'
	                    }
	                }
	            },
	            yAxis: {
	                min: 0,
	                title: {
	                    text: 'Number of Checkouts'
	                }
	            },
	            legend: {
	                enabled: false
	            },
	            tooltip: {
	                formatter: function() {
	                    return '<b>'+ this.x +'</b><br/>'+
	                        'Checkouts: '+ Highcharts.numberFormat(this.y, 0);
	                }
	            },
	            series: [{
	                name: 'Status',
	                data:  <%= ["FACULTY", "FR", "GRAD", "GRAD-NCSU-DIST", "JR", "NCSU-DIST-FR", "NCSU-DIST-JR", "NCSU-DIST-SO", "NCSU-DIST-SR", "SO", "SR", "STAFF", "TRLN", "UNDERGRAD"].map { |status| item.checkouts.where(:patron_status =>status).count}.inspect %>,
	                dataLabels: {
	                    enabled: true,
	                    rotation: -90,
	                    color: '#FFFFFF',
	                    align: 'right',
	                    x: 4,
	                    y: 10,
	                    style: {
	                        fontSize: '13px',
	                        fontFamily: 'Verdana, sans-serif'
	                    }
	                }
	            }]
	        });
	    });
	
	</script>
  <tr class="<%= cycle("odd", "even") -%>">
    <td><%= item.call_number.sub("IQ", "") %></td>
	<td><%= item.call_number %></td>
    <td><%= item.location.sub("UM", "") %></td>
    <% if !item.checkouts.empty? %>
	  <tr>
	    <td class="record_link"><a href="#record">Checkouts: <%= item.checkouts.count %></a>
	   	<br/>
	    <%= item.checkouts.first.date %>-<%= item.checkouts.last.date %>
	 	</td>
	  </tr>    
	  <tr id="<%= item.id.to_s %>" style="display: none">
      	<td class="new_table">
	    	<table>
		    	<tr>
			    	<th>Checkout Date</th>
					<th>Start Time</th>
					<th>End Time</th>
					<th>Patron Status</th>
					<th>Patron College</th>
					<th>Renewals</th>
					<th>Duration</th>
			    </tr>  
			    <% item.checkouts.each do |co| %> 
			    	<tr>
				    	<td><%= co.date %></td>
					    <td><%= co.start_time.strftime("%I:%M%p") %></td>
						<% if !co.end_time.nil? %>
				        	<td><%= co.end_time.strftime("%I:%M%p") %></td>
						<% else %>
							<td><%= co.end_time %></td>
						<% end %>	
				        <td><%= co.patron_status %></td>
				        <td><%= co.patron_college %></td>
				        <td><%= co.renewals %></td>
				        <td><%= co.duration %></td>
			      	</tr>
	     		<% end %>
	   		</table>
		</td>
	  </tr> 
	  <% end %>
  </tr>
<% end %>
</table>
</div>
<% end %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @item.id %>
</p>

<p>
  <b>Call number:</b>
  <%= @item.call_number %>
</p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Location:</b>
  <%= @item.location %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tech Lennding</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application","jquery-1.4.2.min", "highcharts" %>
  <%= csrf_meta_tag %>

<script language="javascript">
$(document).ready(function() {
 $('td.record_link').click(function(){
   $(this).parent().next().toggle();
    return false;
  });
});
</script>
</head>
<body>

<%= yield %>

</body>
</html>